Pandas-series and data frame

In [59]:
import numpy as np
import pandas as pd

In [60]:
# creating a list of price of different medicines
med_price_list = [55,25,75,40,90]

# converting the med_price_list to an array
med_price_arr = np.array(med_price_list)

# converting the list and array into a Pandas Series object
series_list = pd.Series(med_price_list)
series_arr = pd.Series(med_price_arr)

# printing the converted series object
print(series_list)
print(series_arr)

0    55
1    25
2    75
3    40
4    90
dtype: int64
0    55
1    25
2    75
3    40
4    90
dtype: int64

We can see that the list and array have been converted to a Pandas Series object.
We also see that the series has automatically got index labels. Let's see how these can be modified.

In [61]:
# changing the index of a series
med_price_list_labeled = pd.Series(med_price_list, index= ['omeprazole','azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(med_price_list_labeled)

omeprazole      55
azithromycin    25
Metformin       75
Ibuprofen       40
Cetirizine      90
dtype: int64

Performing mathematical operations on Pandas Series

The price of each medicine was increased by $2.5. Let's add this to the existing price.

In [62]:
# adding 2.5 to existing prices
med_price_list_labeled_updated = med_price_list_labeled + 2.5
med_price_list_labeled_updated

omeprazole      57.5
azithromycin    27.5
Metformin       77.5
Ibuprofen       42.5
Cetirizine      92.5
dtype: float64

A new price list was released by vendors for each medicine. Let's find the difference between new price and the old price

In [63]:
new_price_list = [77,45.5,100,50,80]
new_price_list_labeled = pd.Series(new_price_list, index=['Omeprazole','Azithromycin','Metformin','Ibuprofen','Cetirizine'])
print(new_price_list_labeled)

Omeprazole       77.0
Azithromycin     45.5
Metformin       100.0
Ibuprofen        50.0
Cetirizine       80.0
dtype: float64

creating a pandas dataframe using a list

In [64]:
print('difference between new price and old price -')
print(new_price_list_labeled - med_price_list_labeled_updated)

difference between new price and old price -
Azithromycin     NaN
Cetirizine     -12.5
Ibuprofen        7.5
Metformin       22.5
Omeprazole       NaN
azithromycin     NaN
omeprazole       NaN
dtype: float64

**Pandas DataFrame**


Pandas DataFrame is a two-dimensional tabular data structure with labeled axes (rows and columns).



**Creating a Pandas DataFrame using a list**

In [65]:
student = ['mary','peter','susan','toby','vishal']
df1 = pd.DataFrame(student,columns = ['student'])
df1

  student
0    mary
1   peter
2   susan
3    toby
4  vishal

**Creating a Pandas DataFrame using a dictionary**

In [66]:
# defining another list
grades = ['B-', 'A+','A-','B+','C']

# creating the dataframe using a dictionary
df2 = pd.DataFrame({'student': student, 'Grade' : grades})
df2

  student Grade
0    mary    B-
1   peter    A+
2   susan    A-
3    toby    B+
4  vishal     C

**Creating a Pandas DataFrame using Series**



The data for total energy consumption for the U.S. was collected from 2012 - 2018. Let's see how this data can be presented in form of data frame.

In [67]:
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2217,2194,2172,2180,2258])

df3 = pd.DataFrame({'Year':year,'Energy_Consumption(Mtoe)':energy_consumption})
df3

   Year  Energy_Consumption(Mtoe)
0  2012                      2152
1  2013                      2196
2  2014                      2217
3  2015                      2194
4  2016                      2172
5  2017                      2180
6  2018                      2258

**Creating a Pandas DataFrame using random values**




For encryption purposes a web browser company wants to generate random values which have mean equal to 0 and variance equal to 1. They want 5 randomly generated numbers in 2 different trials.

In [68]:
# we can create a new dataframe using random values
df4 = pd.DataFrame(np.random.randn(5,2),columns = ['Trial 1', 'Trial 2'])
df4

    Trial 1   Trial 2
0 -0.896976  0.369267
1 -0.289961  0.618574
2  0.194877  0.478205
3 -0.526244  2.531294
4 -0.889388 -0.966538

**Pandas - Accessing and Modifying**

**Accessing Series**


The revenue (in billion dollars) of different telecommunication operators in U.S. was collected for the year of 2020. The following lists consist of the names of the telecommunication operators and their respective revenue (in billion dollars).

In [69]:
operators = ['AT&T', 'Verizon', 'T-Mobile US', 'US Cellular']
revenue = [171.76, 128.29, 68.4, 4.04]

#creating a Series from lists
telecom = pd.Series(revenue, index=operators)
telecom

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

**Accessing Pandas Series using its index**

In [70]:
# accessing the first element of series
telecom[0]

<ipython-input-70-32d7a3fad61e>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[0]

171.76

In [71]:
#  accessing firt 3 elements of a series
telecom[:3]

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [72]:
# accessing the last two elements of a series
telecom[-2:]

T-Mobile US    68.40
US Cellular     4.04
dtype: float64

In [73]:
# accessing multiple elements of a series
telecom[[0,2,3]]

<ipython-input-73-55a626608097>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[[0,2,3]]

AT&T           171.76
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

**Accessing Pandas Series using its labeled index**

In [74]:
# accessing the revenue of AT&T
telecom['AT&T']

171.76

In [75]:
#  accessing firt 3 revenues of operators in the series
telecom[:'T-Mobile US']

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [76]:
# accessing multiple values
telecom[['AT&T','US Cellular','Verizon']]

AT&T           171.76
US Cellular      4.04
Verizon        128.29
dtype: float64

**Accessing DataFrames**




The data of the customers visiting 24/7 Stores from different locations was collected. The data includes Customer ID, location of store, gender of the customer, type of product purchased, quantity of products purchased, total bill amount. Let's create the dataset and see how to access different entries of it.

In [77]:
# creating the dataframe using dictionary
store_data = pd.DataFrame({'CustomerID': ['CustID00','CustID01','CustID02','CustID03','CustID04']
                           ,'location': ['Chicago', 'Boston', 'Seattle', 'San Francisco', 'Austin']
                           ,'gender': ['M','M','F','M','F']
                           ,'type': ['Electronics','Food&Beverages','Food&Beverages','Medicine','Beauty']
                           ,'quantity':[1,3,4,2,1],'total_bill':[100,75,125,50,80]})
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [78]:
# accessing first row of the dataframe
store_data[:1]

  CustomerID location gender         type  quantity  total_bill
0   CustID00  Chicago      M  Electronics         1         100

In [79]:
# accessing first column of the dataframe
store_data['location']

0          Chicago
1           Boston
2          Seattle
3    San Francisco
4           Austin
Name: location, dtype: object

In [80]:
# accessing rows with the step size of 2
store_data[::2]

  CustomerID location gender            type  quantity  total_bill
0   CustID00  Chicago      M     Electronics         1         100
2   CustID02  Seattle      F  Food&Beverages         4         125
4   CustID04   Austin      F          Beauty         1          80

In [81]:
# accessing the rows in reverse
store_data[::-2]

  CustomerID location gender            type  quantity  total_bill
4   CustID04   Austin      F          Beauty         1          80
2   CustID02  Seattle      F  Food&Beverages         4         125
0   CustID00  Chicago      M     Electronics         1         100

**Using loc and iloc method**


**loc method**


loc is a method to access rows and columns on pandas objects. When using the loc method on a dataframe, we specify which rows and which columns we want by using the following format:

     dataframe.loc[row selection, column selection]


DataFrame.loc[] method is a method that takes only index labels and returns row or dataframe if the index label exists in the data frame.

In [82]:
# accessing first index value using loc method (indexing starts from 0 in python)
store_data.loc[1]

CustomerID          CustID01
location              Boston
gender                     M
type          Food&Beverages
quantity                   3
total_bill                75
Name: 1, dtype: object

**Accessing selected rows and columns using loc method**

In [83]:
# accessing 1st and 4th index values along with location and type columns
store_data.loc[[1,4],['location','type']]

  location            type
1   Boston  Food&Beverages
4   Austin          Beauty

**iloc method**


The iloc indexer for Pandas Dataframe is used for integer location-based indexing/selection by position. When using the loc method on a dataframe, we specify which rows and which columns we want by using the following format:


**dataframe.iloc[row selection, column selection]**

In [84]:
# accessing selected rows and columns using iloc method
store_data.iloc[[1,4],[0,2]]

  CustomerID gender
1   CustID01      M
4   CustID04      F

Difference between loc and iloc indexing methods



     loc is label-based, which means that you have to specify rows and columns based on their row and column labels.
     iloc is integer position-based, so you have to specify rows and columns by their integer position values (0-based integer position).
     

If we use labels instead of index values in .iloc it will throw an error.

In [85]:
# accessing selected rows and columns using iloc method
store_data.iloc[[1,4],['location','type']]

IndexError: .iloc requires numeric indexers, got ['location' 'type']

As expected, .iloc has given error on using 'labels'.

We can modify entries of a dataframe using loc or iloc too

In [86]:
print(store_data.loc[4,'type'])
store_data.loc[4,'type'] = 'Electronics'

Beauty

In [87]:
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F     Electronics         1          80

In [88]:
store_data.iloc[4,3] = 'Beauty'
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [89]:
store_data['quantity']>1

0    False
1     True
2     True
3     True
4    False
Name: quantity, dtype: bool

In [ ]:
store_data.loc[store_data['quantity']>1]

    Wherever the condition is satisfied we get the original values, and wherever the condition is not satisfied we do not get those records in the output.

Column addition and removal from a Pandas DataFrame

Adding a new column in a DataFrame

In [90]:
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

In [ ]:
# adding a new column in data frame store_data which is a rating (out of 5) given by customer based on their shopping experience
store_data['rating'] = [2,5,3,4,4]
store_data

Removing a column from a DataFrame

   The CustomerID column is a unique identifier of each customer. This unique identifier will not help 24/7 Stores in getting useful insights about their customers. So, they have decided to remove this column from the data frame.

In [91]:
store_data.drop('CustomerID',axis=1)

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
1         Boston      M  Food&Beverages         3          75
2        Seattle      F  Food&Beverages         4         125
3  San Francisco      M        Medicine         2          50
4         Austin      F          Beauty         1          80

We sucessfully removed the 'CustomerID' from dataframe. But this change is not permanent in the dataframe, let's have a look at the store_data again.

In [92]:
store_data

  CustomerID       location gender            type  quantity  total_bill
0   CustID00        Chicago      M     Electronics         1         100
1   CustID01         Boston      M  Food&Beverages         3          75
2   CustID02        Seattle      F  Food&Beverages         4         125
3   CustID03  San Francisco      M        Medicine         2          50
4   CustID04         Austin      F          Beauty         1          80

We see that store_data still has column 'CustomerID' in it.
To make permanent changes to a dataframe there are two methods will have to use a parameter inplace and set its value to True.

In [93]:
store_data.drop('CustomerID',axis=1,inplace=True)
store_data

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
1         Boston      M  Food&Beverages         3          75
2        Seattle      F  Food&Beverages         4         125
3  San Francisco      M        Medicine         2          50
4         Austin      F          Beauty         1          80

Now the column has been permanently removed from the dataframe.

In [94]:
# we can also remove multiple columns simultaneously
# it is always a good idea to store the new/updated data frames in new variables to avoid changes to the existing data frame

# creating a copy of the existing data frame
new_store_data = store_data.copy()
store_data

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
1         Boston      M  Food&Beverages         3          75
2        Seattle      F  Food&Beverages         4         125
3  San Francisco      M        Medicine         2          50
4         Austin      F          Beauty         1          80

In [ ]:
# lets check if store_data was impacted
store_data

In [95]:
# dropping location and rating columns simultaneously
new_store_data.drop(['location','rating'],axis=1,inplace=True)
new_store_data

KeyError: "['rating'] not found in axis"

In [96]:
# lets check if store_data was impacted
store_data

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
1         Boston      M  Food&Beverages         3          75
2        Seattle      F  Food&Beverages         4         125
3  San Francisco      M        Medicine         2          50
4         Austin      F          Beauty         1          80

There were no changes to data frame store_data.

Deep copy stores copies of the object’s value.
Shallow Copy stores the references of objects to the original memory address.
Removing rows from a dataframe

In [97]:
store_data.drop(1,axis=0)

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
2        Seattle      F  Food&Beverages         4         125
3  San Francisco      M        Medicine         2          50
4         Austin      F          Beauty         1          80

In [98]:
store_data.drop(1,axis=0)

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
2        Seattle      F  Food&Beverages         4         125
3  San Francisco      M        Medicine         2          50
4         Austin      F          Beauty         1          80

Notice that we used axis=0 to drop a row from a data frame, while we were using axis=1 for dropping a column from the data frame.
Also, to make permanent changes to the data frame we will have to use inplace=True parameter.
We also see that the index are not correct now as first row has been removed. So, we will have to reset the index of the data frame. Let's see how this can be done.

In [99]:
# creating a new dataframe
store_data_new  = store_data.drop(1,axis=0)
store_data_new

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
2        Seattle      F  Food&Beverages         4         125
3  San Francisco      M        Medicine         2          50
4         Austin      F          Beauty         1          80

In [100]:
# resetting the index of data frame
store_data_new.reset_index()

   index       location gender            type  quantity  total_bill
0      0        Chicago      M     Electronics         1         100
1      2        Seattle      F  Food&Beverages         4         125
2      3  San Francisco      M        Medicine         2          50
3      4         Austin      F          Beauty         1          80

We see that the index of the data frame is now resetted but the index has become a column in the data frame. We do not need the index to become a column so we can simply set the parameter drop=True in reset_index() function.

In [101]:
# setting inplace = True to make the changes permanent
store_data_new.reset_index(drop=True,inplace=True)
store_data_new

        location gender            type  quantity  total_bill
0        Chicago      M     Electronics         1         100
1        Seattle      F  Food&Beverages         4         125
2  San Francisco      M        Medicine         2          50
3         Austin      F          Beauty         1          80